apiVersion: apps/v1
kind: Deployment
metadata:
  name: regra-de-tres-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: regra-de-tres
  template:
    metadata:
      labels:
        app: regra-de-tres
    spec:
      containers:
      - name: regra-de-tres
        image: app/regra-de-tres:v1.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: regra
                  operator: In
                  values:
                  - regra-de-tres
    
---
apiVersion: v1
kind: Service
metadata:
  name: regra-de-tres-service
spec:
  selector:
    app: regra-de-tres
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: regra-de-tres-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: regra-de-tres-service
            port: 
              number: 5000
---
